import React from 'react';
import { createRoot } from 'react-dom/client';
import { flushSync } from 'react-dom';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import TailList from './tailList';
import PictogramList from './pictogramList';

// These lists are auto-generated by scripts/build-icon-lib.js from the
// @alaskaairux/icons package (tails: dist/logos/tail-*.svg, pictograms:
// dist/pictograms/*.svg). Each graphic renders as an <img> (kept as its own
// document so the SVGs' internal ids can't collide). The tests assert the
// generated galleries render.

let container;

beforeEach(() => {
  container = document.createElement('div');
  document.body.appendChild(container);
});

afterEach(() => {
  document.body.removeChild(container);
  container = null;
});

const render = (element) => {
  const root = createRoot(container);
  flushSync(() => root.render(element));
  return () => root.unmount();
};

describe('TailList', () => {
  it('renders a Tails section with airline tail icons', () => {
    const unmount = render(<TailList />);
    const html = container.innerHTML;

    expect(html).toContain('Tails');
    // Representative tails from the icon library.
    expect(html).toContain('tail-AS.svg');
    expect(html).toContain('tail-HA.svg');
    // Each tail renders as an <img>. Assert the full set is present without
    // hard-coding an exact count, which would break on any icon-library bump
    // that adds or removes a tail.
    expect(container.querySelectorAll('img').length).toBeGreaterThanOrEqual(50);

    unmount();
  });
});

describe('PictogramList', () => {
  it('renders a Pictograms section with pictogram icons', () => {
    const unmount = render(<PictogramList />);
    const html = container.innerHTML;

    expect(html).toContain('Pictograms');
    expect(html).toContain('elbow-room-on-light.svg');
    expect(container.querySelectorAll('img').length).toBeGreaterThanOrEqual(1);

    unmount();
  });
});
